import type { ZodError } from "zod";

export type ErrorCode =
  | "VALIDATION_ERROR"
  | "AUTH_REQUIRED"
  | "INVALID_CREDENTIALS"
  | "ACCOUNT_SUSPENDED"
  | "ACCOUNT_DEACTIVATED"
  | "WRITER_APPROVAL_REQUIRED"
  | "FORBIDDEN"
  | "CSRF_INVALID"
  | "ORIGIN_INVALID"
  | "RATE_LIMITED"
  | "PAYLOAD_TOO_LARGE"
  | "EMAIL_TAKEN"
  | "USERNAME_TAKEN"
  | "TOPIC_NOT_FOUND"
  | "TOPIC_EXISTS"
  | "TOPIC_CANONICAL_SUGGESTION"
  | "TOPIC_HIDDEN"
  | "TOPIC_MERGED"
  | "ENTRY_NOT_FOUND"
  | "ENTRY_NOT_EDITABLE"
  | "CANNOT_VOTE_OWN_ENTRY"
  | "INVALID_VOTE"
  | "USER_NOT_FOUND"
  | "REPORT_NOT_FOUND"
  | "REPORT_ALREADY_OPEN"
  | "GAMMAZ_CAPABILITY_REQUIRED"
  | "MODERATION_CAPABILITY_REQUIRED"
  | "MODERATION_CONFLICT_OF_INTEREST"
  | "LEGACY_REPORT_READ_ONLY"
  | "MODERATION_DECISION_REQUIRED"
  | "MODERATION_DECISION_TARGET_MISMATCH"
  | "MODERATION_ACTION_NOT_ALLOWED"
  | "MODERATION_ACTION_ALREADY_APPLIED"
  | "TRASH_CASE_NOT_FOUND"
  | "TRASH_CASE_CLOSED"
  | "TRASH_CASE_CONFLICT"
  | "REVIVAL_REQUEST_NOT_FOUND"
  | "REVIVAL_REQUEST_OPEN"
  | "REVIVAL_ALREADY_DECIDED"
  | "REVIVAL_REVISION_REQUIRED"
  | "REVIVAL_REJECTION_REQUIRED"
  | "REVIVAL_ENTRY_VERSION_MISMATCH"
  | "REVIVAL_MODERATION_META"
  | "APPEAL_NOT_FOUND"
  | "APPEAL_ALREADY_SUBMITTED"
  | "APPEAL_ALREADY_DECIDED"
  | "APPEAL_ENTRY_VERSION_MISMATCH"
  | "GAMMAZ_EVIDENCE_NOT_FOUND"
  | "GAMMAZ_EVIDENCE_TARGET_MISMATCH"
  | "GAMMAZ_EVIDENCE_NOT_ACTIVE"
  | "GAMMAZ_EVIDENCE_NOT_DELETED"
  | "CAPABILITY_ALREADY_GRANTED"
  | "CAPABILITY_NOT_GRANTED"
  | "AGENT_MODERATION_NOT_ENABLED"
  | "MODERATION_REASON_REQUIRED"
  | "LAST_ADMIN_GUARD"
  | "IDEMPOTENCY_CONFLICT"
  | "AGENT_NOT_FOUND"
  | "AGENT_RUN_NOT_FOUND"
  | "AGENT_ACTION_NOT_FOUND"
  | "AGENT_ACTION_LIFE_PROPOSAL_EXISTS"
  | "AGENT_ACTION_STATE_INVALID"
  | "AGENT_DECISION_LINK_REQUIRED"
  | "AGENT_LIFE_LEDGER_REQUIRED"
  | "AGENT_SOURCE_NOT_FOUND"
  | "AGENT_MEMORY_NOT_FOUND"
  | "AGENT_MEMORY_INVALIDATED"
  | "AGENT_MEMORY_RECONSOLIDATION_PENDING"
  | "AGENT_RUN_LEASE_INVALID"
  | "AGENT_RUN_CANCEL_REQUESTED"
  | "AGENT_RUN_DEADLINE_EXCEEDED"
  | "AGENT_RUNTIME_ENROLLMENT_UNAVAILABLE"
  | "AGENT_RUNTIME_NOT_READY"
  | "AGENT_RUNTIME_ROSTER_STALE"
  | "AGENT_RUNTIME_ROSTER_INCOMPLETE"
  | "SERVICE_NOT_READY"
  | "AGENT_CAPABILITY_REQUIRED"
  | "AGENT_SETTINGS_VERSION_CONFLICT"
  | "AGENT_DAILY_PLANNING_RETIRED"
  | "AGENT_DUPLICATE_REPAIR_REQUIRED"
  | "AGENT_DUPLICATE_REPAIR_INVALID"
  | "AGENT_LIFECYCLE_INVALID"
  | "PERSONA_ONTOLOGY_REJECTED"
  | "PERSONA_BASELINE_DISTANCE_REJECTED"
  | "PERSONA_PAIRWISE_DISTANCE_REJECTED"
  | "PERSONA_VERSION_NOT_FOUND"
  | "QUOTA_INVALID"
  | "INTERNAL_ERROR";

export class AppError extends Error {
  constructor(
    public readonly code: ErrorCode,
    public readonly status: number,
    message: string,
    public readonly fieldErrors?: Record<string, string[]>,
    public readonly headers?: Record<string, string>,
    public readonly details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = "AppError";
  }
}

export function validationError(error: ZodError): AppError {
  const fieldErrors: Record<string, string[]> = {};
  for (const issue of error.issues) {
    const field = issue.path.join(".") || "form";
    fieldErrors[field] ??= [];
    fieldErrors[field].push(issue.message);
  }
  return new AppError("VALIDATION_ERROR", 422, "Gönderilen bilgiler geçersiz.", fieldErrors);
}
