import type { SeedPersona } from "@/modules/agents/personas/schema";

type PersonaSource = SeedPersona["sources"][number];

/*
  Genişletilmiş doğrulanmış kaynak havuzu (29 Eylül 2026). Paketteki havuz 10 personanın 64
  kaynağından ibaretti ve 36 ajana dağıtıldığında arkitera 33, teyit.org 28, bianet 24 ajanda
  toplanıyordu; aynı haberi 3+ ajanın denediği haberlerde tekrar reddi %40'tı. Buradaki her
  kaynak eklenmeden önce indirildi: HTTP 200, geçerli RSS/Atom, en az 5 öğe ve son 30 günde yayın
  (tarama 29 Eylül 2026) ve projenin `SafeSourceReader` denetiminden geçti (robots.txt ve içerik sinyali reddedenler çıkarıldı). Konu etiketleri ajanların ilgi alanı sözlüğüne göre verildi.
*/
export const expandedVerifiedSources: readonly PersonaSource[] = [
  {
    url: "https://www.nme.com/feed",
    sourceType: "RSS",
    topics: ["müzik", "konser", "albüm"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://pitchfork.com/feed/feed-news/rss",
    sourceType: "RSS",
    topics: ["müzik", "konser", "albüm"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.rollingstone.com/music/feed/",
    sourceType: "RSS",
    topics: ["müzik", "konser", "albüm"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://variety.com/feed/",
    sourceType: "RSS",
    topics: ["film", "dizi", "sinema", "televizyon"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.stereogum.com/feed/",
    sourceType: "RSS",
    topics: ["müzik", "konser", "albüm"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.beyazperde.com/rss/haberler.xml",
    sourceType: "RSS",
    topics: ["film", "dizi", "sinema", "televizyon"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.indiewire.com/feed/",
    sourceType: "RSS",
    topics: ["film", "dizi", "sinema", "televizyon"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.thequietus.com/feed",
    sourceType: "RSS",
    topics: ["müzik", "konser", "albüm"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.edebiyathaber.net/feed/",
    sourceType: "RSS",
    topics: ["kitap", "edebiyat", "yayıncılık"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://lithub.com/feed/",
    sourceType: "RSS",
    topics: ["kitap", "edebiyat", "yayıncılık"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.eater.com/rss/index.xml",
    sourceType: "ATOM",
    topics: ["yemek", "mutfak", "yeme içme"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.webtekno.com/rss.xml",
    sourceType: "RSS",
    topics: ["teknoloji", "gündelik teknoloji", "ürünler"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.donanimhaber.com/rss/tum/",
    sourceType: "RSS",
    topics: ["teknoloji", "gündelik teknoloji", "ürünler"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.theverge.com/rss/index.xml",
    sourceType: "ATOM",
    topics: ["teknoloji", "gündelik teknoloji", "ürünler"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.chip.com.tr/rss",
    sourceType: "RSS",
    topics: ["teknoloji", "gündelik teknoloji", "ürünler"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://feeds.arstechnica.com/arstechnica/index",
    sourceType: "RSS",
    topics: ["teknoloji", "gündelik teknoloji", "ürünler"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.merlininkazani.com/rss",
    sourceType: "RSS",
    topics: ["oyun", "video oyunları"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.technopat.net/feed/",
    sourceType: "ATOM",
    topics: ["teknoloji", "gündelik teknoloji", "ürünler"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.eurogamer.net/feed",
    sourceType: "RSS",
    topics: ["oyun", "video oyunları"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.rockpapershotgun.com/feed",
    sourceType: "RSS",
    topics: ["oyun", "video oyunları"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.log.com.tr/feed/",
    sourceType: "RSS",
    topics: ["teknoloji", "gündelik teknoloji", "ürünler"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.quantamagazine.org/feed/",
    sourceType: "RSS",
    topics: ["bilim", "araştırma"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.theanalyst.com/feed",
    sourceType: "RSS",
    topics: ["spor", "futbol", "spor stratejisi"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.nature.com/nature.rss",
    sourceType: "RSS",
    topics: ["bilim", "araştırma"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.statnews.com/feed/",
    sourceType: "RSS",
    topics: ["sağlık", "bilim ve sağlık"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.medikalakademi.com.tr/feed/",
    sourceType: "RSS",
    topics: ["sağlık", "bilim ve sağlık"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.saglikaktuel.com/rss",
    sourceType: "RSS",
    topics: ["sağlık", "bilim ve sağlık"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.ekoturk.com/feed/",
    sourceType: "RSS",
    topics: ["ekonomi", "gündelik ekonomi", "iş hayatı"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.economist.com/finance-and-economics/rss.xml",
    sourceType: "RSS",
    topics: ["ekonomi", "gündelik ekonomi", "iş hayatı"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.haberturk.com/rss/ekonomi.xml",
    sourceType: "RSS",
    topics: ["ekonomi", "gündelik ekonomi", "iş hayatı"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.ekonomigazetesi.com/rss",
    sourceType: "RSS",
    topics: ["ekonomi", "gündelik ekonomi", "iş hayatı"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.merriam-webster.com/wotd/feed/rss2",
    sourceType: "RSS",
    topics: ["dil", "kelimeler"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.edsurge.com/articles_rss",
    sourceType: "RSS",
    topics: ["eğitim", "öğrenme"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.egitimsen.org.tr/feed/",
    sourceType: "RSS",
    topics: ["eğitim", "öğrenme"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.derintarih.com/feed/",
    sourceType: "RSS",
    topics: ["tarih", "arşiv", "kültür tarihi"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://fstoppers.com/feed",
    sourceType: "RSS",
    topics: ["fotoğraf", "görsel kültür"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.tdk.gov.tr/feed/",
    sourceType: "RSS",
    topics: ["dil", "kelimeler"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.designboom.com/feed/",
    sourceType: "RSS",
    topics: ["tasarım", "mimari", "ürünler"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.dezeen.com/feed/",
    sourceType: "RSS",
    topics: ["tasarım", "mimari", "ürünler"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.raillynews.com/feed/",
    sourceType: "RSS",
    topics: ["ulaşım", "demiryolu", "yolculuk"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.rayhaber.com/feed/",
    sourceType: "RSS",
    topics: ["ulaşım", "demiryolu", "yolculuk"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.iklimhaber.org/feed/",
    sourceType: "RSS",
    topics: ["iklim", "çevre", "enerji"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.carbonbrief.org/feed/",
    sourceType: "RSS",
    topics: ["iklim", "çevre", "enerji"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.tarimdanhaber.com/rss",
    sourceType: "RSS",
    topics: ["tarım", "kırsal hayat", "gıda"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.platformer.news/rss/",
    sourceType: "RSS",
    topics: ["internet kültürü", "çevrimiçi topluluklar", "medya"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.404media.co/rss/",
    sourceType: "RSS",
    topics: ["internet kültürü", "çevrimiçi topluluklar", "medya"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.eff.org/rss/updates.xml",
    sourceType: "RSS",
    topics: ["dijital haklar", "haklar"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://edri.org/feed/",
    sourceType: "RSS",
    topics: ["dijital haklar", "haklar"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.ekoiq.com/feed/",
    sourceType: "RSS",
    topics: ["iklim", "çevre", "enerji"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.niemanlab.org/feed/",
    sourceType: "RSS",
    topics: ["medya", "haber", "gazetecilik"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.poynter.org/feed/",
    sourceType: "RSS",
    topics: ["medya", "haber", "gazetecilik"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.which.co.uk/news/feed",
    sourceType: "RSS",
    topics: ["tüketici hakkı", "tüketici ürünleri", "alışveriş"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://hackaday.com/feed/",
    sourceType: "RSS",
    topics: ["tamir", "bakım ve onarım", "hobi"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.ifixit.com/News/rss",
    sourceType: "RSS",
    topics: ["tamir", "bakım ve onarım", "hobi"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.bonappetit.com/feed/rss",
    sourceType: "RSS",
    topics: ["yemek", "mutfak", "yeme içme"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.loudersound.com/feeds/all",
    sourceType: "RSS",
    topics: ["müzik", "konser", "albüm"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.sporx.com/_xml/rss.php",
    sourceType: "RSS",
    topics: ["spor", "futbol", "spor stratejisi"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.theguardian.com/football/rss",
    sourceType: "RSS",
    topics: ["spor", "futbol", "spor stratejisi"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.fotomac.com.tr/rss/anasayfa.xml",
    sourceType: "RSS",
    topics: ["spor", "futbol", "spor stratejisi"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.bbc.co.uk/sport/football/rss.xml",
    sourceType: "RSS",
    topics: ["spor", "futbol", "spor stratejisi"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
    sourceType: "RSS",
    topics: ["doğa", "çevre", "ekoloji"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.cntraveler.com/feed/rss",
    sourceType: "RSS",
    topics: ["yolculuk", "gezi", "coğrafya"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.theguardian.com/environment/rss",
    sourceType: "RSS",
    topics: ["doğa", "çevre", "ekoloji"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.ajansspor.com/rss",
    sourceType: "RSS",
    topics: ["spor", "futbol", "spor stratejisi"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.wargamer.com/feed",
    sourceType: "RSS",
    topics: ["masa oyunları", "oyun", "hobi"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.atlasobscura.com/feeds/latest",
    sourceType: "RSS",
    topics: ["yolculuk", "gezi", "coğrafya"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.theguardian.com/books/rss",
    sourceType: "RSS",
    topics: ["kitap", "edebiyat", "yayıncılık"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.boardgamewire.com/index.php/feed/",
    sourceType: "RSS",
    topics: ["masa oyunları", "oyun", "hobi"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.smithsonianmag.com/rss/history/",
    sourceType: "RSS",
    topics: ["tarih", "arşiv", "kültür tarihi"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.historyextra.com/feed/",
    sourceType: "RSS",
    topics: ["tarih", "arşiv", "kültür tarihi"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.theguardian.com/science/archaeology/rss",
    sourceType: "RSS",
    topics: ["tarih", "arşiv", "kültür tarihi"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.hurriyet.com.tr/rss/ekonomi",
    sourceType: "RSS",
    topics: ["tarım", "kırsal hayat", "gıda"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.theguardian.com/education/rss",
    sourceType: "RSS",
    topics: ["eğitim", "öğrenme"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.theguardian.com/artanddesign/photography/rss",
    sourceType: "RSS",
    topics: ["fotoğraf", "görsel kültür"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.theguardian.com/cities/rss",
    sourceType: "RSS",
    topics: ["şehir hayatı", "şehir politikaları", "mimarlık"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.theverge.com/rss/tech/index.xml",
    sourceType: "ATOM",
    topics: ["internet kültürü", "çevrimiçi topluluklar", "medya"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.theguardian.com/lifeandstyle/rss",
    sourceType: "RSS",
    topics: ["gündelik hayat", "yaşam"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.bbc.com/turkce/index.xml",
    sourceType: "RSS",
    topics: ["gündelik hayat", "yaşam"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
  {
    url: "https://www.agfundernews.com/feed",
    sourceType: "RSS",
    topics: ["tarım", "kırsal hayat", "gıda"],
    status: "SEED",
    weight: 0.5,
    pinned: false,
  },
] as const satisfies readonly PersonaSource[];

export const expandedTurkishLanguageSourceUrls: readonly string[] = [
  "https://www.ajansspor.com/rss",
  "https://www.bbc.com/turkce/index.xml",
  "https://www.beyazperde.com/rss/haberler.xml",
  "https://www.chip.com.tr/rss",
  "https://www.derintarih.com/feed/",
  "https://www.donanimhaber.com/rss/tum/",
  "https://www.edebiyathaber.net/feed/",
  "https://www.egitimsen.org.tr/feed/",
  "https://www.ekoiq.com/feed/",
  "https://www.ekonomigazetesi.com/rss",
  "https://www.ekoturk.com/feed/",
  "https://www.fotomac.com.tr/rss/anasayfa.xml",
  "https://www.haberturk.com/rss/ekonomi.xml",
  "https://www.hurriyet.com.tr/rss/ekonomi",
  "https://www.iklimhaber.org/feed/",
  "https://www.log.com.tr/feed/",
  "https://www.medikalakademi.com.tr/feed/",
  "https://www.merlininkazani.com/rss",
  "https://www.rayhaber.com/feed/",
  "https://www.saglikaktuel.com/rss",
  "https://www.sporx.com/_xml/rss.php",
  "https://www.tarimdanhaber.com/rss",
  "https://www.tdk.gov.tr/feed/",
  "https://www.technopat.net/feed/",
  "https://www.webtekno.com/rss.xml",
];
